Iter5 - Переменные окружения
dcwk/metrics pull request #5
Opened 2024-03-10 17:06 UTC by dcwk

2024-03-11 16:01 UTC, arttet requested changes
Please add
- https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- https://github.com/golangci/golangci-lint

2024-03-11 16:01 UTC, arttet commented on cmd/agent/main.go
> +var (
CHANGE REQUEST: please don't use global variables

2024-03-11 16:01 UTC, arttet commented on cmd/agent/main.go
> +				r := bytes.NewReader([]byte(""))
CHANGE REQUEST: please split your application by layers.

2024-03-11 16:01 UTC, arttet commented on cmd/agent/main.go
> +func parseFlags() {
SUGGESTION: it would be better if it's in `flags.go`

2024-03-11 16:01 UTC, arttet commented on cmd/agent/main.go
> +			log.Fatalln(err)
CHANGE REQUEST: it's better if you return an error

2024-03-11 19:06 UTC, dcwk commented on cmd/agent/main.go
> +var (
+

2024-03-11 19:07 UTC, dcwk commented on cmd/agent/main.go
> +func parseFlags() {
\+

2024-03-11 19:49 UTC, dcwk commented on cmd/agent/main.go
> +			log.Fatalln(err)
\+

2024-03-11 19:49 UTC, dcwk commented on cmd/agent/main.go
> +				r := bytes.NewReader([]byte(""))
\+

2024-03-12 13:39 UTC, arttet requested changes

2024-03-12 13:39 UTC, arttet commented on internal/client/application.go
> +	var pollCount int64 = 0
```suggestion
	var pollCount int64
```

2024-03-12 13:39 UTC, arttet commented on internal/config/client.go
> +	"github.com/caarlos0/env"
SUGGESTION: please sort imports like there

https://stackoverflow.com/questions/38704769/golang-import-grouping-by-package

2024-03-12 13:39 UTC, arttet commented on internal/config/client.go
> +func NewClientConf() ClientConf {
```suggestion
func NewClientConf() *ClientConf, error {
```

2024-03-12 13:39 UTC, arttet commented on internal/storage/storage.go
> +var (
CHANGE REQUEST: please avoid global variables

2024-03-12 13:39 UTC, arttet commented on internal/handlers/updateMetric.go
> +func UpdateMetric(w http.ResponseWriter, r *http.Request) {
SUGGESTION: you can use it as a method

2024-03-12 13:39 UTC, arttet commented on internal/storage/storage.go
> +func GetStorage() *MemStorage {
CHANGE REQUEST: unfortunately, I don't like singletons

2024-03-12 16:45 UTC, dcwk commented on internal/storage/storage.go
> +func GetStorage() *MemStorage {
\+

2024-03-12 16:46 UTC, dcwk commented on internal/storage/storage.go
> +var (
\+

2024-03-12 16:46 UTC, dcwk commented on internal/config/client.go
> +func NewClientConf() ClientConf {
\+

2024-03-12 16:46 UTC, dcwk commented on internal/client/application.go
> +	var pollCount int64 = 0
\+

2024-03-12 19:52 UTC, dcwk commented on internal/config/client.go
> +	"github.com/caarlos0/env"
\+

2024-03-12 19:53 UTC, dcwk commented on internal/handlers/updateMetric.go
> +func UpdateMetric(w http.ResponseWriter, r *http.Request) {
не понял. Как использовать это как метод?

2024-03-13 15:54 UTC, arttet approved these changes
Great job!

2024-03-13 15:54 UTC, arttet commented on internal/config/client.go
> +	conf := ClientConf{}
```suggestion
	conf := &ClientConf{}
```

2024-03-13 15:54 UTC, arttet commented on internal/config/server.go
> +	conf := ServerConf{}
```suggestion
	conf := &ServerConf{}
```

2024-03-13 15:54 UTC, arttet commented on internal/handlers/getAllMetrics.go
> +func GetAllMetrics(w http.ResponseWriter, r *http.Request, s storage.Storage) {
```suggestion
func (h *Handler) GetAllMetrics(w http.ResponseWriter, r *http.Request) {
```

2024-03-13 15:54 UTC, arttet commented on internal/server/application.go
> +		r.Post("/{type}/{name}/{value}", func(w http.ResponseWriter, r *http.Request) {
SUGGESTION: you can simplify it

2024-03-13 15:54 UTC, arttet commented on internal/storage/storage.go
> +	AddGauge(name string, value string) error
SUGGESTION:

https://go.dev/doc/effective_go

2024-03-13 16:53 UTC, dcwk commented on internal/config/client.go
> +	conf := ClientConf{}
\+

2024-03-13 16:53 UTC, dcwk commented on internal/config/server.go
> +	conf := ServerConf{}
\+

2024-03-14 07:49 UTC, dcwk commented on internal/server/application.go
> +		r.Post("/{type}/{name}/{value}", func(w http.ResponseWriter, r *http.Request) {
\+

2024-04-12 09:57 UTC, merged